# Generated by Django 3.2.8 on 2022-02-18 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='days_running',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='poll',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
